# Generated by Django 4.0.6 on 2022-07-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=20)),
                ('flow', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
