# Generated by Django 4.0.6 on 2022-07-13 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_backend', '0002_rename_location_flows_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='flows',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_backend.category'),
        ),
        migrations.AlterField(
            model_name='flows',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_backend.coordinates'),
        ),
    ]
