# Generated by Django 4.0.6 on 2022-07-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_backend', '0003_category_coordinates_alter_flows_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flows',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flows',
            name='coordinates',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='coordinates',
        ),
    ]
